import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import {
  ArrowUpRight,
  Calendar,
  MapPin,
  X,
  Plus,
  ArrowRight,
  FileText,
  Share2
} from "lucide-react";
import Masonry, {
  ResponsiveMasonry,
} from "react-responsive-masonry";
import { EditableContent } from './cms/EditableContent';
import { EditableCollection } from './cms/EditableCollection';
import { useCMS } from '../context/CMSContext';

const exhibitions = [
  {
    id: 1,
    title: "Neural Landscapes",
    artist: "Elena Kodes",
    role: "Digital Artist",
    year: "2025",
    location: "Ars Electronica, Linz",
    image:
      "https://images.unsplash.com/photo-1545987796-b199d6abb1b4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description:
      "An immersive projection mapping installation exploring the topography of latent spaces in generative adversarial networks. The project utilizes real-time data processing to generate evolving landscapes that react to audience movement.",
    materials: "Projection, TouchDesigner, Kinect",
    tags: ["Generative Art", "Projection", "AI"]
  },
  {
    id: 2,
    title: "Resonant Bodies",
    artist: "Kenji Sato",
    role: "Sound Artist",
    year: "2024",
    location: "Mutek, Montreal",
    image:
      "https://images.unsplash.com/flagged/photo-1574885174114-bd4e8382d850?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description:
      "A spatial audio performance using bio-feedback sensors to translate dancer's muscle movements into low-frequency soundscapes. The body becomes the instrument, conducting a symphony of raw data.",
    materials: "Bio-sensors, Max/MSP, 8-channel Audio",
    tags: ["Sound Art", "Performance", "Bio-feedback"]
  },
  {
    id: 3,
    title: "Ghost in the Machine",
    artist: "Vivien Roussel",
    role: "PhD Student",
    year: "2025",
    location: "Centre Pompidou, Paris",
    image:
      "https://images.unsplash.com/photo-1743119763527-7774bcc1395f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description:
      "Kinetic sculpture series examining the boundary between programmed behavior and emergent personality in swarm robotics. Small autonomous units interact to create complex, unpredictable structures.",
    materials: "Custom PCB, 3D Printed Parts, Motors",
    tags: ["Robotics", "Sculpture", "Swarm"]
  },
  {
    id: 4,
    title: "Infinite Reflection",
    artist: "Xiao Xiao",
    role: "Director",
    year: "2023",
    location: "YCAM, Yamaguchi",
    image:
      "https://images.unsplash.com/photo-1764693948373-9e8aec06222f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description:
      "Interactive mirror installation that distorts time and space based on the viewer's emotional state detected through facial micro-expressions. A study in digital narcissism and self-perception.",
    materials: "OLED, Camera, Emotion AI",
    tags: ["Interactive", "Installation", "AI"]
  },
  {
    id: 5,
    title: "Tactile Dreams",
    artist: "Louis Badr",
    role: "PhD Student",
    year: "2024",
    location: "SIGGRAPH Art Gallery",
    image:
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description:
      "Haptic interface allowing users to feel the texture of digital dreams generated by sleep-monitoring EEG data. Bridging the gap between the conscious and subconscious mind.",
    materials: "Pneumatics, EEG Headset, VR",
    tags: ["Haptics", "VR", "Neuroscience"]
  },
  {
    id: 6,
    title: "Silicon Garden",
    artist: "Sarah Chen",
    role: "Bio-Artist",
    year: "2023",
    location: "Venice Biennale",
    image:
      "https://images.unsplash.com/photo-1743119763527-7774bcc1395f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description:
      "A living ecosystem where plants are grafted with sensors to control their own hydration and light levels. A commentary on the integration of nature and technology.",
    materials: "Plants, Arduino, Hydroponics",
    tags: ["Bio-Art", "Eco-System", "Installation"]
  },
];

export const Arts = () => {
  const { getContent, isEditing } = useCMS();
  const allExhibitions = getContent('arts-exhibitions', exhibitions) as typeof exhibitions;

  const [selectedWork, setSelectedWork] = useState<
    (typeof exhibitions)[0] | null
  >(null);
  const [activeHighlight, setActiveHighlight] = useState(exhibitions[0]);
  const [isHoveringList, setIsHoveringList] = useState(false);

  const featuredWorks = allExhibitions.slice(0, 3);

  return (
    <div className="min-h-screen bg-white text-neutral-900 font-sans selection:bg-teal-200 selection:text-black relative">
      {/* Subtle Grid Lines */}
      <div className="fixed inset-0 z-0 pointer-events-none flex justify-between px-6 md:px-12 xl:px-20 max-w-[1920px] mx-auto opacity-20">
        <div className="w-px h-full bg-neutral-200"></div>
        <div className="w-px h-full bg-neutral-200 hidden md:block"></div>
        <div className="w-px h-full bg-neutral-200 hidden lg:block"></div>
        <div className="w-px h-full bg-neutral-200"></div>
      </div>

      {/* FEATURED ARTS HERO SECTION */}
      <section className="max-w-[1920px] mx-auto min-h-screen flex flex-col lg:flex-row relative z-10">
        
        {/* LEFT COLUMN: List */}
        <div className="lg:w-1/2 p-6 lg:p-12 xl:p-20 pt-32 lg:pt-32 flex flex-col justify-center bg-white/95 backdrop-blur-sm border-r border-neutral-200">
          
          <div className="mb-6">
            <motion.h1 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="text-5xl md:text-7xl font-bold tracking-tighter mb-4 text-neutral-900 leading-[0.9] uppercase"
            >
              <EditableContent
                id="arts-title"
                defaultContent="Arts"
                enableProse={false}
                className="[&_p]:m-0"
              />
            </motion.h1>
            
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              className="text-lg md:text-xl text-neutral-500 font-serif italic mb-12 max-w-lg leading-relaxed"
            >
              <EditableContent
                id="arts-intro"
                defaultContent="Curated exhibitions at the intersection of material reality and digital innovation. Exploring new aesthetics through code and sensors."
                enableProse={false}
                className="[&_p]:m-0"
              />
            </motion.div>
            
            <h2 className="font-mono text-sm uppercase tracking-widest text-neutral-500 mb-2 flex items-center gap-2">
              <span className="w-2 h-2 bg-teal-500 rounded-full animate-pulse"></span>
              <EditableContent
                id="arts-featured-exhibitions-label"
                defaultContent="Featured Exhibitions"
                enableProse={false}
                className="[&_p]:inline [&_p]:m-0"
              />
            </h2>
          </div>

          <div 
            onMouseEnter={() => setIsHoveringList(true)}
            onMouseLeave={() => setIsHoveringList(false)}
          >
            <EditableCollection
              id="arts-exhibitions"
              defaultData={exhibitions}
              displayItems={featuredWorks}
              containerClassName="space-y-0 min-h-[300px]"
              schema={[
                { key: 'title', label: 'Title', type: 'text' },
                { key: 'artist', label: 'Artist', type: 'text' },
                { key: 'year', label: 'Year', type: 'text' },
                { key: 'location', label: 'Location', type: 'text' },
                { key: 'image', label: 'Image', type: 'image' },
                { key: 'description', label: 'Description', type: 'textarea' },
                { key: 'materials', label: 'Materials / Technologies', type: 'text' },
                { key: 'tags', label: 'Tags (comma separated)', type: 'text' },
              ]}
              renderItem={(work, _index, _isEditing) => (
                <AnimatePresence mode="popLayout">
                  <motion.div
                    layout
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -20 }}
                    transition={{ duration: 0.3 }}
                    onMouseEnter={() => setActiveHighlight(work)}
                    className={`group relative py-8 border-t border-neutral-200 cursor-pointer transition-all duration-300 ${
                      activeHighlight.id === work.id ? 'opacity-100' : 'opacity-40 hover:opacity-70'
                    }`}
                  >
                    <div className="flex items-baseline justify-between relative z-10 px-4">
                      <div className="flex items-baseline gap-8">
                        <span
                          className={`font-mono text-xs transition-colors duration-300 ${
                            activeHighlight.id === work.id ? 'text-teal-600' : 'text-neutral-400'
                          }`}
                        >
                          0{work.id}
                        </span>
                        <h3 className="text-2xl md:text-3xl font-light group-hover:translate-x-4 transition-transform duration-500 ease-out text-neutral-900">
                          {work.title}
                        </h3>
                      </div>
                    </div>

                    {activeHighlight.id === work.id && (
                      <motion.div
                        layoutId="activeLine"
                        className="absolute bottom-0 left-0 w-full h-[1px] bg-teal-600"
                      />
                    )}
                  </motion.div>
                </AnimatePresence>
              )}
            />
            <div className="border-t border-neutral-200" />
          </div>

        </div>

        {/* RIGHT COLUMN: Preview (Sticky) */}
        <div className="lg:w-1/2 lg:h-screen lg:sticky lg:top-0 bg-neutral-100 relative overflow-hidden hidden lg:block">
           
           <AnimatePresence mode="wait">
             <motion.div
               key={activeHighlight.id}
               initial={{ opacity: 0 }}
               animate={{ opacity: 1 }}
               exit={{ opacity: 0 }}
               transition={{ duration: 0.5 }}
               className="absolute inset-0 z-0"
             >
                <img 
                  src={activeHighlight.image} 
                  alt={activeHighlight.title}
                  className="w-full h-full object-cover opacity-100 scale-110"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-white via-transparent to-transparent opacity-20" />
             </motion.div>
           </AnimatePresence>

           <div className="absolute inset-0 z-10 p-12 lg:p-20 flex flex-col justify-end">
              <AnimatePresence mode="wait">
                <motion.div
                   key={activeHighlight.id}
                   initial={{ opacity: 0, y: 20 }}
                   animate={{ opacity: 1, y: 0 }}
                   exit={{ opacity: 0, y: -20 }}
                   transition={{ duration: 0.4, ease: "easeOut" }}
                   className="bg-white/90 backdrop-blur-md p-8 md:p-12 border border-white/50 shadow-2xl"
                >
                  <div className="flex flex-wrap gap-2 mb-6">
                    {activeHighlight.tags?.map((tag, i) => (
                      <span key={i} className="px-3 py-1 border border-teal-200 bg-teal-50 rounded-full text-[10px] uppercase tracking-wider text-teal-800">
                        {tag}
                      </span>
                    ))}
                  </div>

                  <h2 className="text-3xl md:text-4xl font-serif leading-tight mb-6 text-neutral-900">
                    {activeHighlight.title}
                  </h2>

                  <div className="flex flex-col gap-1 font-mono text-xs text-neutral-500 mb-6 border-l-2 border-teal-500 pl-4 py-1">
                    <span className="text-neutral-900 font-bold">{activeHighlight.artist}</span>
                    <span>{activeHighlight.location} / {activeHighlight.year}</span>
                  </div>

                  <p className="text-neutral-700 font-sans leading-relaxed text-sm md:text-base mb-4">
                    {activeHighlight.description}
                  </p>
                  
                  <button 
                    onClick={() => setSelectedWork(activeHighlight)}
                    className="mt-4 flex items-center gap-2 text-sm font-bold uppercase tracking-widest text-teal-800 hover:text-teal-600 transition-colors"
                  >
                    View Details <ArrowRight className="w-4 h-4" />
                  </button>
                </motion.div>
              </AnimatePresence>
           </div>
           
           <div className="absolute bottom-8 right-8 font-mono text-[100px] leading-none text-white/20 font-bold z-0 mix-blend-overlay">
              0{activeHighlight.id}
           </div>

        </div>
        
      </section>

      {/* ALL WORKS GRID */}
      <div className="max-w-[1920px] mx-auto px-6 md:px-12 xl:px-20 relative z-10 py-24 border-t border-neutral-200">
        <h2 className="text-4xl md:text-5xl font-serif text-neutral-900 mb-16 text-center">
          <EditableContent
            id="arts-full-archive-title"
            defaultContent="Full Archive"
            enableProse={false}
            className="[&_p]:m-0"
          />
        </h2>

        {isEditing ? (
          <EditableCollection
            id="arts-exhibitions"
            defaultData={exhibitions}
            containerClassName="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-12"
            schema={[
              { key: 'title', label: 'Title', type: 'text' },
              { key: 'artist', label: 'Artist', type: 'text' },
              { key: 'role', label: 'Role', type: 'text' },
              { key: 'year', label: 'Year', type: 'text' },
              { key: 'location', label: 'Location', type: 'text' },
              { key: 'image', label: 'Image', type: 'image' },
              { key: 'description', label: 'Description', type: 'textarea' },
              { key: 'materials', label: 'Materials / Technologies', type: 'text' },
              { key: 'tags', label: 'Tags (comma separated)', type: 'text' },
            ]}
            renderItem={(item: any, index: number) => (
              <motion.div
                initial={{ opacity: 0, y: 50 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.6, delay: index * 0.05 }}
                className="cursor-pointer"
                onClick={() => setSelectedWork(item)}
              >
                <div className="relative overflow-hidden mb-4">
                  <img
                    src={item.image}
                    alt={item.title}
                    className="w-full h-auto object-cover transition-all duration-700 group-hover:scale-105"
                  />
                </div>
                <div className="flex flex-col gap-1 border-t border-transparent group-hover:border-neutral-200 pt-4 transition-colors duration-300">
                  <div className="flex justify-between items-baseline">
                    <h3 className="text-xl font-medium group-hover:text-teal-600 transition-colors duration-300">
                      {item.title}
                    </h3>
                    <span className="font-mono text-xs text-neutral-400">{item.year}</span>
                  </div>
                  <p className="text-sm text-neutral-500 font-sans">{item.artist}</p>
                  <p className="text-xs text-neutral-400 font-mono uppercase mt-1">{item.location}</p>
                </div>
              </motion.div>
            )}
          />
        ) : (
          <ResponsiveMasonry columnsCountBreakPoints={{ 350: 1, 750: 2, 1200: 3 }}>
            <Masonry gutter="40px">
              {allExhibitions.map((item, index) => (
                <motion.div
                  key={item.id}
                  initial={{ opacity: 0, y: 50 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-50px" }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                  className="group cursor-pointer mb-20"
                  onClick={() => setSelectedWork(item)}
                >
                  <div className="relative overflow-hidden mb-4">
                    <img
                      src={item.image}
                      alt={item.title}
                      className="w-full h-auto object-cover grayscale-0 transition-all duration-700 group-hover:scale-105"
                    />
                  </div>
                  <div className="flex flex-col gap-1 border-t border-transparent group-hover:border-neutral-200 pt-4 transition-colors duration-300">
                    <div className="flex justify-between items-baseline">
                      <h3 className="text-xl font-medium group-hover:text-teal-600 transition-colors duration-300">
                        {item.title}
                      </h3>
                      <span className="font-mono text-xs text-neutral-400">{item.year}</span>
                    </div>
                    <p className="text-sm text-neutral-500 font-sans">{item.artist}</p>
                    <p className="text-xs text-neutral-400 font-mono uppercase mt-1">{item.location}</p>
                  </div>
                </motion.div>
              ))}
            </Masonry>
          </ResponsiveMasonry>
        )}
      </div>

      {/* Modal / Lightbox */}
      <AnimatePresence>
        {selectedWork && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 lg:p-8">
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setSelectedWork(null)}
              className="absolute inset-0 bg-neutral-900/60 backdrop-blur-sm"
            />
            
            <motion.div 
              layoutId={`work-${selectedWork.id}`}
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="bg-white w-full max-w-5xl max-h-[90vh] overflow-y-auto relative z-10 shadow-2xl flex flex-col md:flex-row"
            >
              <button 
                onClick={() => setSelectedWork(null)}
                className="absolute top-4 right-4 z-20 p-2 bg-white/50 hover:bg-white rounded-full transition-colors"
              >
                <X className="w-6 h-6 text-neutral-900" />
              </button>

              {/* Media Section - Left Side (Landscape/Rectangular) */}
              <div className="w-full md:w-1/2 aspect-video md:aspect-auto md:h-auto bg-neutral-100 relative flex-shrink-0">
                <img 
                  src={selectedWork.image} 
                  alt={selectedWork.title} 
                  className="w-full h-full object-cover"
                />
                <div className="absolute top-4 left-4 bg-white/90 px-3 py-1 text-xs font-mono uppercase tracking-wider border border-neutral-100">
                  {selectedWork.year}
                </div>
              </div>

              {/* Content Section - Right Side */}
              <div className="flex-grow p-8 md:p-12 flex flex-col overflow-y-auto">
                <div className="mb-6">
                  <div className="flex flex-wrap gap-2 mb-4">
                    {selectedWork.tags.map((tag: any, i: number) => (
                      <span key={i} className="px-2 py-1 bg-teal-50 text-teal-700 text-[10px] uppercase tracking-wider border border-teal-100 rounded-sm">
                        {tag}
                      </span>
                    ))}
                  </div>
                  
                  <h2 className="text-3xl md:text-4xl font-serif text-neutral-900 mb-4 leading-tight">
                    {selectedWork.title}
                  </h2>
                  
                  <div className="flex flex-col gap-1 font-mono text-xs text-neutral-500 mb-8 border-l-2 border-teal-500 pl-4 py-1">
                    <span className="text-neutral-900 font-bold">{selectedWork.artist}</span>
                    <span>Exhibited at {selectedWork.location}</span>
                  </div>

                  <div className="prose prose-neutral prose-sm max-w-none mb-8">
                    <p className="text-neutral-600 leading-relaxed text-base">
                      {selectedWork.description}
                    </p>
                  </div>

                  <div className="bg-neutral-50 p-6 border border-neutral-100 mb-8">
                    <span className="block text-xs uppercase text-neutral-400 mb-2 font-mono">
                      Materials / Technologies
                    </span>
                    <p className="font-mono text-sm text-neutral-700">
                      {selectedWork.materials}
                    </p>
                  </div>
                </div>

                <div className="mt-auto pt-8 border-t border-neutral-100 flex gap-4">
                  <button className="flex items-center gap-2 bg-neutral-900 text-white px-6 py-3 hover:bg-teal-600 transition-all duration-300 uppercase text-xs font-bold tracking-widest flex-1 justify-center relative overflow-hidden group shadow-lg hover:shadow-2xl hover:shadow-teal-500/20">
                    <span className="absolute inset-0 w-0 bg-gradient-to-r from-transparent via-white/20 to-transparent group-hover:w-full transition-all duration-700 ease-out"></span>
                    <FileText className="w-4 h-4 relative z-10" />
                    <span className="relative z-10">View Portfolio</span>
                  </button>
                  <button className="flex items-center gap-2 border border-neutral-200 text-neutral-900 px-6 py-3 hover:bg-neutral-50 hover:border-teal-400 transition-all duration-300 uppercase text-xs font-bold tracking-widest flex-1 justify-center hover:shadow-md">
                     <Share2 className="w-4 h-4" />
                     Share
                  </button>
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
};