import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { X, Edit2 } from "lucide-react";
import Masonry, {
  ResponsiveMasonry,
} from "react-responsive-masonry";
import { EditableContent } from './cms/EditableContent';
import { EditableCollection, EditModal } from './cms/EditableCollection';
import { EditableImageSingle } from './cms/EditableImageSingle';
import { CardButtons } from './CardButtons';
import { useCMS } from '../context/CMSContext';
import { useBodyScrollLock } from '../hooks/useBodyScrollLock';

export const defaultExhibitions = [
  {
    id: 1,
    title: "Neural Landscapes",
    artist: "Elena Kodes",
    role: "Digital Artist",
    year: "2025",
    location: "Ars Electronica, Linz",
    image:
      "https://images.unsplash.com/photo-1545987796-b199d6abb1b4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description:
      "An immersive projection mapping installation exploring the topography of latent spaces in generative adversarial networks. The project utilizes real-time data processing to generate evolving landscapes that react to audience movement.",
    materials: "Projection, TouchDesigner, Kinect",
    tags: ["Generative Art", "Projection", "AI"]
  },
  {
    id: 2,
    title: "Resonant Bodies",
    artist: "Kenji Sato",
    role: "Sound Artist",
    year: "2024",
    location: "Mutek, Montreal",
    image:
      "https://images.unsplash.com/flagged/photo-1574885174114-bd4e8382d850?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description:
      "A spatial audio performance using bio-feedback sensors to translate dancer's muscle movements into low-frequency soundscapes. The body becomes the instrument, conducting a symphony of raw data.",
    materials: "Bio-sensors, Max/MSP, 8-channel Audio",
    tags: ["Sound Art", "Performance", "Bio-feedback"]
  },
  {
    id: 3,
    title: "Ghost in the Machine",
    artist: "Vivien Roussel",
    role: "PhD Student",
    year: "2025",
    location: "Centre Pompidou, Paris",
    image:
      "https://images.unsplash.com/photo-1743119763527-7774bcc1395f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description:
      "Kinetic sculpture series examining the boundary between programmed behavior and emergent personality in swarm robotics. Small autonomous units interact to create complex, unpredictable structures.",
    materials: "Custom PCB, 3D Printed Parts, Motors",
    tags: ["Robotics", "Sculpture", "Swarm"]
  },
  {
    id: 4,
    title: "Infinite Reflection",
    artist: "Xiao Xiao",
    role: "Director",
    year: "2023",
    location: "YCAM, Yamaguchi",
    image:
      "https://images.unsplash.com/photo-1764693948373-9e8aec06222f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description:
      "Interactive mirror installation that distorts time and space based on the viewer's emotional state detected through facial micro-expressions. A study in digital narcissism and self-perception.",
    materials: "OLED, Camera, Emotion AI",
    tags: ["Interactive", "Installation", "AI"]
  },
  {
    id: 5,
    title: "Tactile Dreams",
    artist: "Louis Badr",
    role: "PhD Student",
    year: "2024",
    location: "SIGGRAPH Art Gallery",
    image:
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description:
      "Haptic interface allowing users to feel the texture of digital dreams generated by sleep-monitoring EEG data. Bridging the gap between the conscious and subconscious mind.",
    materials: "Pneumatics, EEG Headset, VR",
    tags: ["Haptics", "VR", "Neuroscience"]
  },
  {
    id: 6,
    title: "Silicon Garden",
    artist: "Sarah Chen",
    role: "Bio-Artist",
    year: "2023",
    location: "Venice Biennale",
    image:
      "https://images.unsplash.com/photo-1743119763527-7774bcc1395f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080",
    description:
      "A living ecosystem where plants are grafted with sensors to control their own hydration and light levels. A commentary on the integration of nature and technology.",
    materials: "Plants, Arduino, Hydroponics",
    tags: ["Bio-Art", "Eco-System", "Installation"]
  },
];

const exhibitionsSchema = [
  { key: 'title', label: 'Title', type: 'text' },
  { key: 'artist', label: 'Artist', type: 'text' },
  { key: 'role', label: 'Role', type: 'text' },
  { key: 'year', label: 'Year', type: 'text' },
  { key: 'location', label: 'Location', type: 'text' },
  { key: 'image', label: 'Image', type: 'image' },
  { key: 'description', label: 'Description', type: 'textarea' },
  { key: 'materials', label: 'Materials / Technologies', type: 'text' },
  { key: 'tags', label: 'Tags (comma separated)', type: 'text' },
];

const ArtsSkeleton = () => (
  <div className="min-h-screen bg-white animate-pulse">
    <section className="max-w-[1920px] mx-auto min-h-screen flex flex-col lg:flex-row">
      <div className="lg:w-1/2 p-6 lg:p-12 xl:p-20 pt-16 md:pt-20 lg:pt-24 flex flex-col justify-center border-r border-neutral-200">
        <div className="h-12 md:h-16 bg-neutral-200 rounded w-32 mb-4" />
        <div className="space-y-3 max-w-xl">
          <div className="h-4 bg-neutral-100 rounded w-full" />
          <div className="h-4 bg-neutral-100 rounded w-full" />
          <div className="h-4 bg-neutral-100 rounded w-3/4" />
          <div className="h-4 bg-neutral-100 rounded w-full mt-6" />
          <div className="h-4 bg-neutral-100 rounded w-5/6" />
        </div>
      </div>
      <div className="lg:w-1/2 lg:h-screen bg-neutral-100 hidden lg:block" />
    </section>
  </div>
);

export const Arts = () => {
  const { getContent, updateContent, isEditing, canEditKey, isLoading, hasCache } = useCMS();

  if (isLoading && !hasCache) {
    return <ArtsSkeleton />;
  }
  const allExhibitions = getContent('arts-exhibitions', defaultExhibitions) as typeof defaultExhibitions;
  const visibleExhibitions = isEditing ? allExhibitions : (Array.isArray(allExhibitions) ? allExhibitions : []).filter((i: any) => !i.hidden);

  const [selectedWork, setSelectedWork] = useState<
    (typeof defaultExhibitions)[0] | null
  >(null);
  const [editingWorkInModal, setEditingWorkInModal] = useState(false);

  useBodyScrollLock(!!selectedWork);
  const canEditExhibitions = isEditing && canEditKey('arts-exhibitions');

  const handleSaveWorkEdit = (updated: any) => {
    if (!selectedWork) return;
    const list = [...(Array.isArray(allExhibitions) ? allExhibitions : [])];
    const idx = list.findIndex((p: any) => (p.id && selectedWork.id && p.id === selectedWork.id) || p === selectedWork);
    if (idx === -1) return;
    const tagsVal = updated.tags;
    const item = {
      ...selectedWork,
      ...updated,
      tags: typeof tagsVal === 'string' ? tagsVal.split(',').map((s: string) => s.trim()).filter(Boolean) : tagsVal,
    };
    list[idx] = item;
    updateContent('arts-exhibitions', list);
    setSelectedWork(item);
    setEditingWorkInModal(false);
  };

  return (
    <div className="min-h-screen bg-white text-neutral-900 font-sans selection:bg-teal-200 selection:text-black relative">
      {/* Subtle Grid Lines */}
      <div className="fixed inset-0 z-0 pointer-events-none flex justify-between px-6 md:px-12 xl:px-20 max-w-[1920px] mx-auto opacity-20">
        <div className="w-px h-full bg-neutral-200"></div>
        <div className="w-px h-full bg-neutral-200 hidden md:block"></div>
        <div className="w-px h-full bg-neutral-200 hidden lg:block"></div>
        <div className="w-px h-full bg-neutral-200"></div>
      </div>

      {/* FEATURED ARTS HERO SECTION */}
      <section className="max-w-[1920px] mx-auto min-h-screen flex flex-col lg:flex-row relative z-10">
        
        {/* LEFT COLUMN: Title + Blurb */}
        <div className="lg:w-1/2 p-6 lg:p-12 xl:p-20 pt-16 md:pt-20 lg:pt-24 flex flex-col justify-center bg-white/95 backdrop-blur-sm border-r border-neutral-200">
          
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-4xl md:text-6xl font-bold tracking-tighter mb-4 text-neutral-900 leading-[0.9] uppercase"
            role="heading"
            aria-level={1}
          >
            <EditableContent
              id="arts-title"
              defaultContent="Arts"
              enableProse={false}
              className="[&_p]:m-0"
            />
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-lg md:text-xl text-neutral-600 font-sans leading-relaxed max-w-xl space-y-4"
          >
            <EditableContent
              id="arts-blurb-1"
              defaultContent="Curated exhibitions at the intersection of material reality and digital innovation. Our Arts programme explores new aesthetics through code, sensors, and emerging technologies—from immersive projection mapping and spatial audio to kinetic sculpture and bio-art."
              enableProse={true}
              className="[&_p]:m-0"
            />
            <EditableContent
              id="arts-blurb-2"
              defaultContent="We support artists and researchers who blur the boundaries between computation and craft, presenting work at venues including Ars Electronica, Centre Pompidou, SIGGRAPH, and the Venice Biennale."
              enableProse={true}
              className="[&_p]:m-0"
            />
          </motion.div>

        </div>

        {/* RIGHT COLUMN: Hero Image (Sticky) */}
        <div className="lg:w-1/2 lg:h-screen lg:sticky lg:top-0 bg-neutral-100 relative overflow-hidden hidden lg:block">
           <div className="absolute inset-0 z-0">
             <EditableImageSingle
               id="arts-hero-image"
               defaultImage={visibleExhibitions[0]?.image ?? "https://images.unsplash.com/photo-1545987796-b199d6abb1b4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080"}
               alt="Arts hero"
               className="w-full h-full object-cover opacity-100"
             />
             <div className="absolute inset-0 bg-gradient-to-t from-white via-transparent to-transparent opacity-20 pointer-events-none" />
           </div>
        </div>
        
      </section>

      {/* ALL WORKS GRID */}
      <div className="max-w-[1920px] mx-auto px-6 md:px-12 xl:px-20 relative z-10 py-24 border-t border-neutral-200">
        <div className="text-4xl md:text-5xl font-serif text-neutral-900 mb-16 text-center" role="heading" aria-level={2}>
          <EditableContent
            id="arts-full-archive-title"
            defaultContent="Full Archive"
            enableProse={false}
            className="[&_p]:m-0"
          />
        </div>

        {isEditing ? (
          <EditableCollection
            id="arts-exhibitions"
            defaultData={defaultExhibitions}
            containerClassName="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 md:gap-12"
            schema={exhibitionsSchema}
            renderItem={(item: any, index: number) => (
              <motion.div
                initial={{ opacity: 0, y: 50 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.6, delay: index * 0.05 }}
                className="cursor-pointer touch-pan-y"
                onClick={() => setSelectedWork(item)}
              >
                <div className="relative overflow-hidden mb-4">
                  <img
                    src={item.image}
                    alt={item.title}
                    className="w-full h-auto object-cover transition-all duration-700 group-hover:scale-105 pointer-events-none select-none"
                  />
                </div>
                <div className="flex flex-col gap-1 border-t border-transparent group-hover:border-neutral-200 pt-4 transition-colors duration-300">
                  <div className="flex justify-between items-baseline">
                    <h3 className="text-xl font-medium group-hover:text-teal-600 transition-colors duration-300">
                      {item.title}
                    </h3>
                    <span className="font-mono text-xs text-neutral-400">{item.year}</span>
                  </div>
                  <p className="text-sm text-neutral-500 font-sans">{item.artist}</p>
                  <p className="text-xs text-neutral-400 font-mono uppercase mt-1">{item.location}</p>
                </div>
              </motion.div>
            )}
          />
        ) : (
          <ResponsiveMasonry columnsCountBreakPoints={{ 350: 1, 750: 2, 1200: 3 }}>
            <Masonry gutter="24px">
              {visibleExhibitions.map((item, index) => (
                <motion.div
                  key={item.id}
                  initial={{ opacity: 0, y: 50 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, margin: "-50px" }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                  className="group cursor-pointer mb-8 md:mb-20 touch-pan-y min-w-0"
                  onClick={() => setSelectedWork(item)}
                >
                  <div className="relative overflow-hidden mb-4">
                    <img
                      src={item.image}
                      alt={item.title}
                      className="w-full h-auto object-cover grayscale-0 transition-all duration-700 group-hover:scale-105 pointer-events-none select-none"
                    />
                  </div>
                  <div className="flex flex-col gap-1 border-t border-transparent group-hover:border-neutral-200 pt-4 transition-colors duration-300">
                    <div className="flex justify-between items-baseline">
                      <h3 className="text-xl font-medium group-hover:text-teal-600 transition-colors duration-300">
                        {item.title}
                      </h3>
                      <span className="font-mono text-xs text-neutral-400">{item.year}</span>
                    </div>
                    <p className="text-sm text-neutral-500 font-sans">{item.artist}</p>
                    <p className="text-xs text-neutral-400 font-mono uppercase mt-1">{item.location}</p>
                  </div>
                </motion.div>
              ))}
            </Masonry>
          </ResponsiveMasonry>
        )}
      </div>

      {/* Modal / Lightbox */}
      <AnimatePresence>
        {selectedWork && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 lg:p-8">
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setSelectedWork(null)}
              onTouchMove={(e) => e.preventDefault()}
              className="absolute inset-0 bg-neutral-900/60 backdrop-blur-sm touch-none"
            />
            
            <motion.div 
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="bg-white w-full max-w-5xl max-h-[90vh] overflow-hidden relative z-10 shadow-2xl"
            >
              <div className="absolute top-4 right-4 z-20 flex items-center gap-2">
                {canEditExhibitions && (
                  <button onClick={() => setEditingWorkInModal(true)} className="p-2 bg-teal-100 hover:bg-teal-200 rounded-full transition-colors text-teal-700" title="Edit exhibition">
                    <Edit2 className="w-5 h-5" />
                  </button>
                )}
                <button onClick={() => { setSelectedWork(null); setEditingWorkInModal(false); }} className="p-2 bg-white/50 hover:bg-white rounded-full transition-colors">
                  <X className="w-6 h-6 text-neutral-900" />
                </button>
              </div>

              <div className="max-h-[90vh] overflow-y-auto md:overflow-hidden modal-scroll flex flex-col md:flex-row">
              {/* Media Section - Left Side (Landscape/Rectangular) */}
              <div className="w-full md:w-1/2 aspect-video md:aspect-auto md:h-auto bg-neutral-100 relative flex-shrink-0">
                <img 
                  src={selectedWork.image} 
                  alt={selectedWork.title} 
                  className="w-full h-full object-cover"
                />
                <div className="absolute top-4 left-4 bg-white/90 px-3 py-1 text-xs font-mono uppercase tracking-wider border border-neutral-100">
                  {selectedWork.year}
                </div>
              </div>

              {/* Content Section - Right Side */}
              <div className="flex-grow p-4 sm:p-6 md:p-8 lg:p-12 flex flex-col min-h-0">
                <div className="flex-1 min-h-0 overflow-y-auto pr-2">
                  <div className="mb-6">
                  <div className="flex flex-wrap gap-2 mb-4">
                    {(Array.isArray(selectedWork.tags) ? selectedWork.tags : (selectedWork.tags || '').split(',')).map((tag: any, i: number) => (
                      <span key={i} className="px-2 py-1 bg-teal-50 text-teal-700 text-[10px] uppercase tracking-wider border border-teal-100 rounded-sm">
                        {tag}
                      </span>
                    ))}
                  </div>
                  
                  <h2 className="text-3xl md:text-4xl font-serif text-neutral-900 mb-4 leading-tight">
                    {selectedWork.title}
                  </h2>
                  
                  <div className="flex flex-col gap-1 font-mono text-xs text-neutral-500 mb-8 border-l-2 border-teal-500 pl-4 py-1">
                    <span className="text-neutral-900 font-bold">{selectedWork.artist}</span>
                    <span>Exhibited at {selectedWork.location}</span>
                  </div>

                  <div className="prose prose-neutral prose-sm max-w-none mb-8">
                    <p className="text-neutral-600 leading-relaxed text-base">
                      {selectedWork.description}
                    </p>
                  </div>

                  <div className="bg-neutral-50 p-6 border border-neutral-100 mb-8">
                    <span className="block text-xs uppercase text-neutral-400 mb-2 font-mono">
                      Materials / Technologies
                    </span>
                    <p className="font-mono text-sm text-neutral-700">
                      {selectedWork.materials}
                    </p>
                  </div>
                </div>
                </div>

                <CardButtons
                  item={selectedWork}
                  defaultButtons={[
                    { label: 'View Portfolio', primary: true },
                    { label: 'Share', primary: false },
                  ]}
                />
              </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      <EditModal isOpen={editingWorkInModal} onClose={() => setEditingWorkInModal(false)} onSave={handleSaveWorkEdit} data={selectedWork || {}} schema={exhibitionsSchema} title="Edit Exhibition" />
    </div>
  );
};